### ISSUE TITLE
bug fixed where PCs write cell vectors instead of char vectors for h5 (map) attributes

### ISSUE THREAD

**Issue by edwardbair** [edwardbair/SPIRES#1]
Jeff, 

Seems to happen going from PC to Linux, e.g. Quinaya to Truyi. Can't find any issues with the way the attributes are written.

See l 21-23 and 50-52 of [GetCoordinateInfo.m](https://github.com/edwardbair/SPIRES/blob/master/MODIS_HDF/GetCoordinateInfo.m)

**Comment by DozierJeff** [comment]
Ah, interesting.
One issue with HDF 5, back when I wrote those codes, is that I didn’t find any guidance about how one should incorporate projection information and referencing matrix (or raster reference) in an HDF 5 file. With geoTIFFs, there are explicit places in the geotiffinfo. The problem though with geoTIFFs is that the format itself doesn’t enable compression so you have to go through that step separately, and the Landsat images come in .gz format with .tar embedded. HDF 5 supports block compression, so you can extract a piece of a dataset without uncompressing the whole file. So you can put out a whole year’s reconstruction and pull out just a short sequence of days. I recall asking Karl if NSIDC has any documentation; at the time the answer was No.
I’m at Donner Pass visiting my sister and brother-in-law. Home in Mammoth tomorrow.

Jeff Dozier dozier@ucsb.edu<mailto:dozier@ucsb.edu>
805-563-2336
