### ISSUE TITLE
check waterConc vs wetness here

### ISSUE THREAD

**Issue by edwardbair** [edwardbair/SPIRES#5]
https://github.com/edwardbair/SPIRES/blob/6ee31db3acec07cd89a71f5affb4202ab217bdc9/toolbox/SnowCloudReflectance/SnowCloudSpectralRefl.m#L85

**Comment by DozierJeff** [comment]
SnowCloudSpectralRefl is a deprecated function, replaced by SPIReS_fwd. Wait for updates.
