### ISSUE TITLE
source of offset band of fsca=0 in L8 SPIRES

### ISSUE THREAD

**Issue by Timbo-Stillinger** [edwardbair/SPIRES#7]
https://github.com/edwardbair/SPIRES/blob/7ac8eb6a9076f8fdac561c4cbfb3132199a6c557/run_spires.m#L178
https://github.com/edwardbair/SPIRES/blob/7ac8eb6a9076f8fdac561c4cbfb3132199a6c557/run_spires.m#L180

Hey Ned, 

I think this is the source of the band of fsca=0 in some of the L8 spires outputs. The issue is when R and R0 do not align, which is often, i.e. the edge of the swath is different on the two dates. In line 178 of the code when the matrix is filled up with the answers, fsca=0 gets pasted into areas where R0=valid measurement but R=NaN. It is different than Line 76 to 78, which correctly nans out the areas where R=NaN and R0=valid. 

https://github.com/edwardbair/SPIRES/blob/7ac8eb6a9076f8fdac561c4cbfb3132199a6c557/run_spires.m#L76

Prior to get_spires, the nanmask is only based on  R0 - line 74 and line 124 of run_spires_landsat.m, so we just need to figure out a better way to account for the fact that along the swath edges R and R0 might no have 1:1 matches of valid measurements, either can have NaNs when the other has surface reflectance, and those should all be Nan's.

**Comment by edwardbair** [comment]
Ok, I think its fixed. I removed the check for null values in R and R0 in run_spires_landsat.  Those values are now checked for and skipped in run_spires. What I failed to realize is that even if you reproject R and R0 to match, there can still be null values in one where the other doesn't have nulls. Thanks for the help.
